version: '3.7'

# Starts these services:
#   webapp, a flask app that responds to HTTP on port 9999

networks:
  proxy_net:
    name: proxy_net
    external: true

services:
  webapp:
    image: wildsong/flask:latest
    build:
      context: .
      dockerfile: Dockerfile.webhooks
    env_file: .env
    environment:
      PYTHONPATH: /srv
      FLASK_APP: start_app
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${MY_EMAIL}
    command: ["flask", "run"]
    volumes:
      - .:/srv
    ports:
      - "8443:5000"
    user: app
    networks:
      proxy_net:
        aliases:
          - webhooks

